case_statuses = {
    "filed": {
        "name": "Case Filed",
        "owner": "Client",
        "mandatory": True,
        "short_description": "Case Filed on Casenet",
        "internal_status": "Case Filed",
        "client_status": "",
        "next_case_status": "",
    },
    "paid": {
        "name": "Case Payment",
        "owner": "Client",
        "mandatory": True,
        "flag": "todo",
        "short_description": "Client Paid",
        "internal_status": "Payment Received",
        "client_status": "",
        "next_case_status": "REVIEW",
        "color": "orange",
    },
    "review": {
        "name": "Case Review and Consultation",
        "owner": "Lawyer",
        "mandatory": True,
        "flag": "todo",
        "short_description": "Case Under Review",
        "internal_status": "Under Review",
        "client_status": "",
        "next_case_status": "REJECTED, EOA",
        "color": "orange",
    },
    "rejected": {
        "name": "Case Rejected",
        "owner": "Lawyer",
        "mandatory": False,
        "flag": "pending",
        "short_description": "Case Rejected",
        "internal_status": "Case cannot be handled by our attorneys",
        "client_status": "",
        "next_case_status": "REFUND",
        "color": "red",
    },
    "refund": {
        "name": "Case Refund",
        "owner": "Lawyer",
        "mandatory": False,
        "flag": "closed",
        "short_description": "Case Refunded",
        "internal_status": "We initiated a full refund. It should be reflected in your account within 5-10 business days. We apologize for any inconvenience.",
        "client_status": "",
        "next_case_status": "CLOSURE",
        "color": "red",
    },
    "sign_engagement_letter": {
        "name": "Sign Engagement Letter",
        "owner": "Client, Lawyer",
        "mandatory": True,
        "flag": "pending",
        "short_description": "Engagement Letter Sign-Off",
        "internal_status": "Case Accepted",
        "client_status": "Our Attorneys have accepted your case",
        "next_case_status": "EOA",
        "color": "orange",
    },
    "warrant_status": {
        "name": "Warrant Status",
        "owner": "Lawyer",
        "mandatory": False,
        "flag": "pending",
        "short_description": "Recall Warrant",
        "internal_status": "Warrant",
        "client_status": "",
        "next_case_status": "REV_INT",
        "color": "orange",
    },
    "eoa": {
        "name": "Entry of Appearance",
        "owner": "Lawyer",
        "mandatory": True,
        "flag": "todo",
        "short_description": "EOA",
        "internal_status": "Our Attorneys are Working on the Case",
        "client_status": "",
        "next_case_status": "REV_INT, CLIENT_REQUEST",
        "color": "green",
    },
    "client_request": {
        "name": "Documentation Request from the Customer",
        "owner": "Client",
        "mandatory": True,
        "flag": "pending",
        "short_description": "Client Intake Form",
        "internal_status": "Our Attorneys have requested more information from you on your case",
        "client_status": "",
        "next_case_status": "REV_INT",
        "color": "orange",
    },
    "court_response": {
        "name": "Court Response",
        "owner": "Lawyer",
        "mandatory": False,
        "flag": "pending",
        "short_description": "Court Response",
        "internal_status": "Our Attorneys are Working on the Case",
        "client_status": "",
        "next_case_status": "REV_INT",
        "color": "orange",
    },
    "rev_int": {
        "name": "Case Documentation & Information Gathering",
        "owner": "Lawyer",
        "mandatory": True,
        "flag": "todo",
        "short_description": "Internal Review",
        "internal_status": "Our Attorneys are gathering documentation to back your case",
        "client_status": "",
        "next_case_status": "DEFENSE_REV",
        "color": "orange",
    },
    "defense_dev": {
        "name": "Case Legal Strategy Development",
        "owner": "Lawyer",
        "mandatory": True,
        "flag": "pending",
        "short_description": "Review with the Client",
        "internal_status": "Our attorneys are elaborating a strategy to defend your cause",
        "client_status": "",
        "next_case_status": "REC_REQUEST",
        "color": "orange",
    },
    "rec_request": {
        "name": "Case Request for Recommendation",
        "owner": "Lawyer",
        "mandatory": True,
        "flag": "todo",
        "short_description": "RFR Filing",
        "internal_status": "Attorney has initiated negotiations with the Prosecutor",
        "client_status": "",
        "next_case_status": "REC_RECEIVED, REC_DELAYED, REC_REJECT",
    },
    "rec_received": {
        "name": "Case Request for Recommendation",
        "owner": "Prosecutor",
        "mandatory": False,
        "flag": "todo",
        "short_description": "Recommendation Received",
        "internal_status": "Attorney has negotiated a favorable plea offer",
        "client_status": "",
        "next_case_status": "REC_REVIEW",
        "color": "green",
    },
    "rec_reject": {
        "name": "Case Request for Recommendation",
        "owner": "Prosecutor",
        "mandatory": False,
        "flag": "todo",
        "short_description": "Recommendation Rejected",
        "internal_status": "Case cannot be handled by our attorneys",
        "client_status": "",
        "next_case_status": "REFUND",
        "color": "red",
    },
    "rec_delay": {
        "name": "Case Request for Recommendation",
        "owner": "Prosecutor",
        "mandatory": False,
        "flag": "todo",
        "short_description": "Recommendation Delayed",
        "internal_status": "The Prosecutor has delayed providing a plea offer. Please provide the information requested",
        "client_status": "",
        "next_case_status": "CLIENT_REQUEST, REC_RECEIVED, REC_REVIEW",
        "color": "orange",
    },
    "rec_review": {
        "name": "Case Plea Negotiation with the Prosecutor (if applicable)",
        "owner": "Lawyer",
        "mandatory": False,
        "flag": "todo",
        "short_description": "Recommendation Review",
        "internal_status": "The Attorney has initiated further negotiations with the prosecutor",
        "client_status": "",
        "next_case_status": "REC_REVIEW, REC_PROPOSAL",
    },
    "rec_proposal": {
        "name": "Case Recommendation Proposal",
        "owner": "Client",
        "mandatory": True,
        "flag": "pending",
        "short_description": "Recommendation Proposed to Client",
        "internal_status": "Attorney has negotiated a favorable plea offer and would like you to review and accept the plea offer",
        "client_status": "",
        "next_case_status": "SIG_REQUIRED",
        "color": "green",
    },
    "sig_required": {
        "name": "Case pending Signature and Payment",
        "owner": "Client",
        "mandatory": True,
        "flag": "pending",
        "short_description": "Recommendation pending Signature",
        "internal_status": "Client signature and payment are required to accept the Prosecutor's Plea Offer",
        "client_status": "",
        "next_case_status": "SUB",
        "color": "orange",
    },
    "sub": {
        "name": "Case Recommendation and Payment Submission to Court",
        "owner": "Lawyer",
        "mandatory": True,
        "flag": "todo",
        "short_description": "Recommendation to Submit to Court",
        "internal_status": "Attorney is submitting the signed plea and payment to the court for approval",
        "client_status": "",
        "next_case_status": "SUB_REVIEW",
        "color": "green",
    },
    "sub_review": {
        "name": "Case Recommendation and Payment Review by the Court",
        "owner": "Court",
        "mandatory": True,
        "flag": "pending",
        "short_description": "Recommendation Submission under Review by the Court",
        "internal_status": "Plea Offer is pending Court Approval",
        "client_status": "",
        "next_case_status": "APPEAR, CLOSE",
    },
    "appear": {
        "name": "Court Representation (if applicable)",
        "owner": "Lawyer",
        "mandatory": False,
        "flag": "pending",
        "short_description": "Court Appearance Required",
        "internal_status": "Court is requiring an appearance to approve the plea",
        "client_status": "",
        "next_case_status": "CLOSE",
    },
    "close": {
        "name": "Case Closure",
        "owner": "Lawyer",
        "mandatory": True,
        "flag": "pending",
        "short_description": "Close Case on Portal",
        "internal_status": "Congratulations! Case closed",
        "client_status": "",
        "next_case_status": "CLIENT_REVIEW",
    },
    "client_review": {
        "name": "Case Feedback",
        "owner": "Client",
        "mandatory": False,
        "flag": "closed",
        "short_description": "Client Submits Review",
        "internal_status": "Please provide us with a review and feedback from your experience",
        "client_status": "",
        "next_case_status": "CLIENT_FEEDBACK",
        "color": "green",
    },
}


def get_case_status_color(status: str | None):
    if status is None:
        return "gray"

    status_details = case_statuses.get(status)

    if status_details is None:
        return "gray"

    return status_details.get("color", "gray")
